# Generated by Django 5.1.6 on 2025-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empoly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('Specilastion', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
